---
kind: Template
apiVersion: v1
metadata:
  name: onionbalance
parameters:
- name: PRIVATE_KEY
  description: "base64 of the generate RSA 1024 key, ex: openssl genrsa 1024 | base64 |tr -d '\\n'"
  required: true
- name: UNIQUE_NAME
  description: "Unique name to identify secrets and configmap for this app"
  required: false
  generate: expression
  from: "[a-z0-9]{10}"
- name: ONION_INSTANCES
  description: "List of .onion to loadbalance. Ex: [ address: hbvlni32fc32v7zw.onion, address: 6bztlzyrm7lhzy2g.onion ]. You can leave it and edit the configmap later if you prefer."
  required: false
  value: "[]"
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: onionshift
    name: alpine
  spec:
    tags:
    - annotations:
        openshift.io/imported-from: alpine
      from:
        kind: DockerImage
        name: alpine
      generation: null
      importPolicy: {}
      name: latest
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: onionshift
    name: onionshift
  spec: {}
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: onionshift
    name: onionshift
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: onionshift:latest
    postCommit: {}
    resources: {}
    source:
      git:
        uri: https://github.com/fridim/onionshift
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: alpine:latest
      type: Docker
    triggers:
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
- apiVersion: v1
  data:
    ${UNIQUE_NAME}.key: ${PRIVATE_KEY}
  kind: Secret
  metadata:
    name: ${UNIQUE_NAME}.key
  type: Opaque
- apiVersion: v1
  data:
    ${UNIQUE_NAME}.conf: |
      TOR_ADDRESS: 127.0.0.1
      TOR_PORT: 9051
      STATUS_SOCKET_LOCATION: /data/onionbalance/control
      services:
      - instances: ${ONION_INSTANCES}
        key: ${UNIQUE_NAME}.key
  kind: ConfigMap
  metadata:
    name: ${UNIQUE_NAME}.conf
- apiVersion: v1
  kind: ConfigMap
  data:
    torrc: |
      DataDirectory /data/tor

      ControlPort 9051
      CookieAuthentication 1
      SocksPort 0
      CookieAuthFile /data/shared/control_auth_cookie
  metadata:
    name: ${UNIQUE_NAME}-torrc
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: onionbalance-${UNIQUE_NAME}
  spec:
    replicas: 1
    template:
      metadata:
        name: onionbalance
        labels:
          app: onionbalance
      spec:
        containers:
        - name: tor
          image: "onionshift:latest"
          ports:
          - containerPort: 9051
            name: controlport
          volumeMounts:
          - mountPath: /etc/tor
            name: torrc
          - mountPath: /data/shared
            name: volume-data-tor
        - name: onionbalance
          image: "onionshift:latest"
          command:
          - /onionbalance-entrypoint.sh
          volumeMounts:
          - mountPath: /data/shared
            name: volume-data-tor
          - mountPath: /data/import-key
            name: masterkey
          - mountPath: /data/import-conf
            name: masterconf
        volumes:
        - name: volume-data-tor
          emptyDir:
        - name: torrc
          configMap:
            name: ${UNIQUE_NAME}-torrc
        - name: masterkey
          secret:
            secretName: ${UNIQUE_NAME}.key
        - name: masterconf
          configMap:
            name: ${UNIQUE_NAME}.conf
            items:
            - key: ${UNIQUE_NAME}.conf
              path: config.yaml
    triggers:
      - type: "ConfigChange" 
      - type: "ImageChange" 
        imageChangeParams:
          automatic: true
          containerNames:
          - tor
          from:
            kind: "ImageStreamTag"
            name: "onionshift:latest"
      - type: "ImageChange" 
        imageChangeParams:
          automatic: true
          containerNames:
          - onionbalance
          from:
            kind: "ImageStreamTag"
            name: "onionshift:latest"
